"use strict";
//connect
console.log("Flashcard App Connected");
//The Reproductive System-KeyTerms

/* Change the questions to whatever you want!*/
var questions=[
    "To give life to a new person",
    "The female and male external organs of reproduction.",
    "The female's reproductive body that joins the internal and external female reproductive organs and structures and it is the entry way for penetration during sexual intercourse",
    "The internal female reproductive structure that lies just above the vagina and houses a developing fetus during pregnancy and after fertilization.",
    "The layer of the uterus which covers the entire uterus",
    "The middle layer of the uterus",
    "The innermost layer of the uterus that has glands that secrete a substance to transport sperm and to provide a developing embryo with essential nutrients",
    "They serve as a reproductive gland that produces ova and also an endocrine gland during pregnancy, prior to puberty and throughout the duration of time from puberty to menopause",
    "The part of the female reproductive system that is the site of the fertilization of the ovum.",
    "An alternative name for the fallopian tubes",
    "The hair like fringes of the fallopian tubes nearest to the ovaries",
    "The section of the fallopian tubes that lies between the isthmus and the ampulla of the fallopian tube",
    "The innermost layer of the ovaries that contains the nerves and blood supply to the ovaries",
    "The middle layer of the ovaries that contains the follicles and ova or female eggs",
    "The outermost layer of the ovaries that protects the ovaries",
    "The labia that form the larger and outer perimeter around the vaginal opening and the labia minora",
    "The labia that form the smaller and inner perimeter around the vaginal opening",
    "It lies above the vagina this structure is covered with a protective cover or hood; it is one of a female's primary organs of sexual gratification and pleasure",
    "The opening to the urethra which is part of the urinary system",
    "Provides sexual satisfaction and gratification to the male",
    "The tip of the penis which is protected with foreskin unless a circumcision has been done",
    "This sac holds and protects the testes",
    "Endocrine and reproductive organs",
    "Connects the testes and the vas deferens stores and transports and matures the sperm from the testes.",
    "Moves the mature sperm from the epididymis to the ejaculatory ducts",
    "An exocrine gland that secretes an alkaline fluid that preserves the life of the sperm when it hits the acidic female vagina.",
    "They form the union of the vas deferens and the seminal vesicles; sperm enters the ejaculatory ducts from the vas deferens.",
    "A part of both the male reproductive system and a gland of the genitourinary or urinary system",
    "Produces sperm (spermatogenesis)",
    "Produces testosterone",
    "The hormone that leads to the development of primary and secondary sexual characteristics during puberty",
    "Cancer affecting the breast tissue",
    "Cancer of the cervix",
    "Cancer of the ovary",
    "Infection of the vagina and vaginal vault",
    "The growth of the lining of the uterus outside of the uterus itself",
    "A serious infection of the female reproductive organs including the fallopian tubes, the ovaries, the uterus and the vagina",
    "The collapse of the urinary bladder into the vagina",
    "The pushing of the rectum and part of the large intestine against the vaginal wall",
    "The hypertrophy of the male prostate",
    "Cancer of the male prostate gland",
    "Cancer of a testicle or both testes",
    "A low level of circulating testosterone among males",
    "The inability of a male to have and maintain an erection",
    "What?"
    ];

var answers=[
    "Procreate: ",
    "Genitalia: ",
    "Vagina:",
    "Uterus:",
    "Perimetrium:",
    "Myometrium: ",
    "Endometrium:",
    "Ovaries: ",
    "Fallopian tubes:",
    "Salpinges:",
    "Fimbria: ",
    "Ampulla:",
    "Medulla:",
    "Cortex:",
    "Tunica albuginea: ",
    "Labia majora:",
    "Labia minora: ",
    "Clitoris:",
    "Urethral meatus:",
    "Penis:",
    "Glans penis:",
    "Scrotum: ",
    "Testes:",
    "Epididymis:",
    "Vas deferens:",
    "Prostate: ",
    "Ejaculatory Ducts: ",
    "Urethra:",
    "Follicle stimulating hormone:",
    "Luteinizing hormone:",
    "Testosterone:",
    "Cancer of the breast:",
    "Cervical cancer:",
    "Ovarian cancer:",
    "Vaginitis:",
    "Endometriosis:",
    "Pelvic inflammatory disease:",
    "Cystocele:",
    "Rectocele:",
    "Enlarged prostate:",
    "Prostate cancer:",
    "Testicular cancer:",
    "Low testosterone: ",
    "Erectile dysfunction:",
    "Next!"
];