"use strict";
//connect
console.log("Flashcard App Connected");
//Cardiovascular System-KeyTerms

/* Change the questions to whatever you want! Remember to stick to the theme of music this month. */
var questions=[
    "What?",
    "F01: A pulse rate of less than 60 per minute",
    "F02: A pulse rate of more than 100 per minute",
    "F03: The phase of the cardiac cycle when the heart is contracting and 'at work'",
    "F04: The phase of the cardiac cycle when the heart is at rest",
    "F05: The sac that encloses the heart; the heart's outermost layer",
    "F06: The middle layer of the heart that is muscular and referred to as cardiac muscles",
    "F07: The innermost layer of the heart that also lines the heart valves and other heart structures",
    "F08: Bundles of nerve tissues that allows the heart to conduct nerve impulses",
    "F09: The top of the heart on the right side of the heart that receives deoxygenated blood from the superior vena cava and the inferior vena cava",
	"F10: The top of the heart on the left side of the heart holds richly oxygenated blood from the right and the left pulmonary veins from the lung",
    "F11: The bottom of the heart on the right side of the heart that receives deoxygenated blood from the right atria and it then pumps it from the heart to the lungs",
    "F12: The bottom of the heart on the left side of the heart that receives oxygenated blood from the left atria and it then pumps it from the heart to the rest of the body through the aorta",
    "F13: Anatomical structures inside the heart that separate and control the blood flow from one of the heart chambers to another heart chamber or major vessel like the aorta",
    "F14: The atrioventricular valve that separates and controls the blood flow from the left atria of the heart to the left ventricle of the heart without any backflow",
    "F15: The atrioventricular valve that separates and controls the blood flow from the right atria of the heart to the right ventricle of the heart without any backflow",
	"F16: The semilunar valve that separates and controls the blood flow from the right ventricle of the heart to the pulmonary artery without any backflow",
    "F17: The semilunar valve that separates and controls the blood flow from the left ventricle of the heart to the aorta without any backflow",
    "F18: The rate of the heart is documented as the number of heartbeats per minute",
    "F19: The natural heart pacemaker of the heart that controls the rate of the heart, initiates and begins the cardiac cycle, and sends an electrical impulse to the atrioventricular (AV) node",
    "F20: This node sends an electrical impulse to the bundle of His",
    "F21: This sends an electrical impulse to a bundle of nerve fibers called the Purkinje fibers",
    "F22: This bundle of nerves innervates, or leads to, the contraction of the right and left ventricles",
    "F23: Abnormal and irregular heartbeats",
    "F24: Also referred to as an EKG or ECG, it records the electrical activity of the heart and the heart's rhythm",
	"F25: The wave on an EKG or ECG that represents atrial depolarization and atrial contraction during atrial systole",
    "F26: Also called the PR segment, it is the space on the EKG or ECG between the P wave and the R of the QRS complex",
    "F27: The wave on an EKG or ECG that represents atrial repolarization and ventricular depolarization.",
    "F28: The space on the EKG or ECG between the S and the T wave.",
    "F29: The space between the beginning of the Q wave and the end of the T wave.",
    "F30: The wave on an EKG or ECG that represents the repolarization of the ventricles.",
    "F31: The EKG or ECG wave that represents the repolarization of the Purkinje fibers",
    "F32: High blood pressure",
    "F33: Low blood pressure",
	"F34: Chest pain that results from the lack of adequate oxygen to the heart muscle. The lack of oxygen to the heart muscle is referred to as ischemia.",
	"F35: Damage to the coronary or heart arteries. Coronary artery disease results from the build-up of plaque (atherosclerosis) in the coronary arteries. This build-up of plaque leads to smaller and narrower vessels that are needed to supply the heart with its needed oxygenation and blood flow. Coronary artery disease is signaled with chest pain (angina)",
	"F36: Heart attack",
	"F37: Disorders that adversely affect the normal flow of blood from the right and left atria to the right and left ventricles of the heart and/or from the right and left ventricles to the pulmonary artery and the aorta, respectively.",
	"F38: The invasion of a pathogen, or germ, that infects the heart.",
	"F39: Irregular heartbeats that can adversely affect the functioning of the heart and the transmission of its electrical impulse; some cardiac arrhythmias are life-threatening.",
    "F40: Irregular heartbeats that can adversely affect the functioning of the heart and the transmission of its electrical impulse; some cardiac dysrhythmias are life-threatening."
    ];

var answers=[
    "Yes, Great!",
    "C01: Bradycardia",
    "C02: Tachycardia",
    "C03: Systole",
    "C04: Diastole",
    "C05: Pericardium",
    "C06: Myocardium",
    "C07: Endocardium",
    "C08: Purkinje fibers",
    "C09: Right atrium",
	"C10: Left atrium",
	"C11: Right ventricle",
    "C12: Left ventricle",
    "C13: Heart valves",
    "C14: Bicuspid or mitral valve",
    "C15: Tricuspid valve",
    "C16: Pulmonary valve",
    "C17: Aortic valve",
    "C18: Pulse",
    "C19: Sinoatrial (SA) node",
	"C20: Atrioventricular(AV)node",
	"C21: Bundle of His",
    "C22: Purkinje fibers",
    "C23: Cardiac arrhythmia, or dysrhythmia",
    "C24: Electrocardiogram",
    "C25: P wave",
    "C26: PR interval",
    "C27: QRS complex",
    "C28: ST segment",
    "C29: The QT interval",
	"C30: T wave",
	"C31: U wave",
    "C32: Hypertension",
    "C33: Hypotension",
    "C34: Angina or angina pectoris",
    "C35: Coronary artery disease",
    "C36: Myocardial infarction",
    "C37: Heart valve disorders",
    "C38: Heart infections",
    "C39: Cardiac arrhythmias",
    "C40: Cardiac dysrhythmias"
];

