"use strict";
//connect
console.log("Flashcard App Connected");
//Basic Terminology-KeyTerms

/* Change the questions to whatever you want! Remember to stick to the theme of music this month. */
var questions=[
    "What?",
    "F01: The study of the parts and structures of the human body that can be seen with the naked eye and without the use of a microscope",
    "F02: The study of the parts and structures of the human body that can NOT be seen with the naked eye and only seen with the use of a microscope",
    "F03: Also referred to as the coronal plane, separates the front from the back of the body.",
    "F04: The front of the body",
    "F05: The back of the body",
    "F06: Also referred to as the cross sectional plane separates the top of the body at the waist from the bottom of the body",
    "F07: Also referred to as the medial plane separates the right side of the body from the left side of the body",
    "F08: Closer to the front of the body than another bodily part",
    "F09: Further from the front of the body than another bodily part",
	"F10: One bodily part is above another bodily par",
	"F11: One bodily part is below another bodily par",
	"F12: A subdivision of microscopic anatomy that is the study of the parts and structures of the body's cells",
	"F13: A subdivision of microscopic anatomy that is the study of the parts and structures of the body's tissues",
	"F14: The basic building blocks of the human body and the bodies of all other living species",
	"F15: One of the two types of cells that don't have organelles or a nucleus",
	"F16: One of the two types of cells that have a nucleus containing genetic material and organelles",
	"F17: The area around the cell that protects the cell membrane and the cell from threats in its external environment",
	"F18: The environment outside of a cell",
	"F19: Inside the cell",
	"F20: The ability of the cell to let particles into the cells and to get particles out of the cell",
	"F21: Electrically charged molecules such as electrolytes in the human body",
	"F22: Electrolytes that have a negative electrical charge",
	"F23: Electrolytes that have positive electrical charge",
	"F24: The covering that envelopes cells and somewhat acts like the gate keeper of the cell.",
	"F25: The substance which makes up the bulk of a living cell and contains the organelles",
	"F26: The part of the cell that maintains the shape and form of the cell",
	"F27: The place in the cell that contains chromosomes and the place where both DNA and RNA are synthesized and replicated.",
	"F28: The 'mini organs' in the cell that perform a specific role.",
	"F29: This organelle produces and stores energy in the form of adenosine triphosphate (ATP) with a complex cycle of production known as the Krebs's cycle",
	"F30: The organelle that breaks down and disposes of cellular wastes",
	"F31: The organelle that synthesizes proteins and lipids",
	"F32: The organelle that processes and stores the proteins and lipids that it receives from the endoplasmic reticulum",
	"F33: The organelle that synthesize protein with the linking of different amino acids as per the instructions of the messenger RNA molecules",
	"F34: The movement of molecules across membranes that does NOT require the use of cellular energy to perform this transport",
	"F35: The movement of molecules across membranes that requires the use of cellular energy to perform this transport",
	"F36: The movement of molecule from an area of higher concentration to the area or side of the membrane that has the lesser concentration",
	"F37: A type of passive transport that does NOT require the use of cellular energy to move water and solute particles",
	"F38: Cell division where the resulting cells have half of the original number of chromosomes",
	"F39: Cell division where the nucleus of the cell replicates itself into two identical copies of itself",
	"F40: A group of cells with similar structure that join together to perform a specialized function",
	"F41: Also referred to as epithelium, it is the type of tissue that skin and glands are made of",
	"F42: The type of tissue that ligaments, tendons and bones are made of",
	"F43: Striated muscle that enables voluntary bodily movement",
	"F44: Muscle that is not striated and not under voluntary control",
	"F45: Striated, involuntary muscle that is found only in the heart. This tissue enables cardiac functioning.",
	"F46: Neural tissue in the central and peripheral nervous systems",
	"F47: A self-contained group of tissues that serves at least one bodily function to maintain normal bodily functioning and the homeostasis, or balance, of the body.",
    "F48: Groups of bodily tissues that group together to perform specific roles and functions in the body to maintain its homeostasis"  
    ];

var answers=[
    "Yes - Basic Terms",
    "C01: Gross anatomy",
    "C02: Microscopic anatomy",
    "C03: The frontal plane",
    "C04: Ventral surface",
    "C05: Dorsal surface",
    "C06: Transverse plane",
    "C07: Sagittal plane",
    "C08: Anterior",
    "C09: Posterior",
	"C10: Superior",
	"C11: Inferior",
	"C12: Cytology",
	"C13: Histology",
	"C14: Cell",
	"C15: Prokaryotes",
	"C16: Eukaryotes",
	"C17: Cell wall",
	"C18: Extracellular",
	"C19: Intracellular",
	"C20: Permeability",
	"C21: Ions",
	"C22: Anions",
	"C23: Cations",
	"C24: Cell membrane",
	"C25: Cytoplasm",
	"C26: Cytoskeleton",
	"C27: Cell nucleus",
	"C28: Organelles",
	"C29: Mitochondria",
	"C30: Lysosomes",
	"C31: Endoplasmic reticulum",
	"C32: Golgi apparatus",
	"C33: Ribosomes",
	"C34: Passive transport",
	"C35: Active transport",
	"C36: Diffusion",
	"C37: Osmosis",
	"C38: Meiosis",
	"C39: Mitosis",
	"C40: Tissues",
	"C41: Epithelial tissue",
	"C42: Connective tissue",
	"C43: Skeletal muscle tissue",
	"C44: Smooth muscle tissue",
	"C45: Cardiac muscle tissue",
	"C46: Nervous tissue",
	"C47: Organs",
    "C48: Bodily systems"
    
];
