"use strict";
//connect
console.log("Flashcard App Connected");
//Reproductive System - Terms and Terminology

/* Change the questions to whatever you want! Remember to stick to the theme of music this month. */
var questions=[
    "What?",
    "F01: To give life to a new person",
    "F02: The female and male external organs of reproduction are referred to as _________.",
    "F03: The female's reproductive body that joins the internal and external female reproductive organs and structures and it is the entry way for penetration during sexual intercourse",
    "F04: The internal female reproductive structure that lies just above the vagina and houses a developing fetus during pregnancy and after fertilization.",
    "F05: The layer of the uterus which covers the entire uterus",
    "F06: The middle layer of the uterus",
    "F07: The innermost layer of the uterus that has glands that secrete a substance to transport sperm and to provide a developing embryo with essential nutrients",
    "F08: They serve as a reproductive gland that produces ova and also an endocrine gland during pregnancy, prior to puberty and throughout the duration of time from puberty to menopause",
    "F09: The part of the female reproductive system that is the site of the fertilization of the ovum.",
	"F10: An alternative name for the fallopian tubes",
    "F11: The hair like fringes of the fallopian tubes nearest to the ovaries",
    "F12: The section of the fallopian tubes that lies between the isthmus and the ampulla of the fallopian tube",
    "F13: The innermost layer of the ovaries that contains the nerves and blood supply to the ovaries",
    "F14: The middle layer of the ovaries that contains the follicles and ova or female eggs",
    "F15: The outermost layer of the ovaries that protects the ovaries",
    "F16: The labia that form the larger and outer perimeter around the vaginal opening and the labia minora",
    "F17: The labia that form the smaller and inner perimeter around the vaginal opening",
    "F18: It lies above the vagina this structure is covered with a protective cover or hood; it is one of a female's primary organs of sexual gratification and pleasure",
	"F19: The opening to the urethra which is part of the urinary system",
	"F20: Provides sexual satisfaction and gratification to the male",
	"F21: The tip of the penis which is protected with foreskin unless a circumcision has been done",
	"F22: This sac holds and protects the testes",
	"F23: Endocrine and reproductive organs",
	"F24: Connects the testes and the vas deferens stores and transports and matures the sperm from the testes.",
	"F25: Moves the mature sperm from the epididymis to the ejaculatory ducts",
	"F26: An exocrine gland that secretes an alkaline fluid that preserves the life of the sperm when it hits the acidic female vagina.",
	"F27: They form the union of the vas deferens and the seminal vesicles; sperm enters the ejaculatory ducts from the vas deferens",
	"F28: A part of both the male reproductive system and a gland of the genitourinary or urinary system",
	"F29: Produces sperm (spermatogenesis)",
	"F30: Produces testosterone",
	"F31: The hormone that leads to the development of primary and secondary sexual characteristics during puberty",
	"F32: Cancer affecting the breast tissue",
	"F33: Cancer of the cervix",
	"F34: Cancer of the ovary",
	"F35: Infection of the vagina and vaginal vault",
	"F36: The growth of the lining of the uterus outside of the uterus itself",
	"F37: A serious infection of the female reproductive organs including the fallopian tubes, the ovaries, the uterus and the vagina",
	"F38: The collapse of the urinary bladder into the vagina",
	"F39: The pushing of the rectum and part of the large intestine against the vaginal wall",
	"F40: The hypertrophy of the male prostate",
	"F41: Cancer of the male prostate gland",
	"F42: Cancer of a testicle or both testes",
	"F43: A low level of circulating testosterone among males",
	"F44: The inability of a male to have and maintain an erection"
    ];

var answers=[
    "Yes. Great!",
    "C01: Procreate",
    "C02: Genitalia",
    "C03: Vagina",
    "C04: Uterus",
    "C05: Perimetrium",
    "C06: Myometrium",
    "C07: Endometrium",
    "C08: Ovaries",
    "C09: Fallopian tubes",
	"C10: Salpinges",
	"C11: Fimbria",
    "C12: Ampulla",
    "C13: Medulla",
    "C14: Cortex",
    "C15: Tunica albuginea",
    "C16: Labia majora",
    "C17: Labia minora",
    "C18: Clitoris",
    "C19: Urethral meatus",
	"C20: Penis",
	"C21: Glans penis",
	"C22: Scrotum",
	"C23: Testes",
	"C24: Epididymis",
	"C25: Vas deferens",
	"C26: Prostate",
	"C27: Ejaculatory Ducts",
	"C28: Urethra",
	"C29: Follicle stimulating hormone",
	"C30: Luteinizing hormone",
	"C31: Testosterone",
	"C32: Cancer of the breast",
    "C33: Cervical cancer",
    "C34: Ovarian cancer",
    "C35: Vaginitis",
    "C36: Endometriosis",
    "C37: Pelvic inflammatory disease",
    "C38: Cystocele",
    "C39: Rectocele",
	"C40: Enlarged prostate",
	"C41: Prostate cancer",
    "C42: Testicular cancer",
    "C43: Low testosterone",
    "C44: Erectile dysfunction"
];

