"use strict";
//connect
console.log("Flashcard App Connected");
//Endocrine System-KeyTerms

/* Change the questions to whatever you want!*/
var questions=[
    "The endocrine system consists of these glands:",
    "Natural chemical substances that control, manage and coordinate several bodily functions throughout the body",
    "An organ that secretes and releases a substance.",
    "A gland that secretes a substance to the exterior part of the body",
    "A gland that secretes and releases hormones into the blood which goes to target organ(s) in the body",
    "Bodily balance",
    "Also referred to as the 'master gland', this endocrine system gland is housed near the base of the skull just above the pituitary gland and it performs several roles",
    "The endocrine system gland that is housed near the base of the skull just below the hypothalamus gland that performs several roles",
    "The small endocrine system gland that is in the brain and relatively close to the hypothalamus and the pituitary glands of the endocrine system and that regulates sleep and wake cycles",
    "The normal human being's 24 hour cycle of sleep and wakefulness.",
    "Day time active and nighttime sleep beings",
    "Nighttime active and daytime sleep beings",
    "The endocrine system gland that lies in the neck and secretes several endocrine hormones",
    "The four endocrine system glands that lie on both sides of the thyroid gland in the neck and that control the amount of circulating calcium and phosphorous, which are two electrolytes",
    "The endocrine system glands that lies in the abdominal area above the diaphragm and just above the kidneys that secrete several hormones from its cortex and its medulla",
    "The outer layer of the adrenal glands that secretes androgen, aldosterone and cortisol",
    "The inner layer of the adrenal glands that secretes adrenaline, noradrenaline and catecholamine",
    "The endocrine system gland that is located behind the stomach that plays an important role in our control of blood sugar with insulin from this gland",
    "The endocrine system and reproductive system gland that produces progesterone, estrogen, inhibin and androstenedione",
    "The ovarian hormone that is secreted by the ovaries and plays a role in the menstrual cycle and the preparation of the uterus for the implantation of the fertilized egg or ovum",
    "The ovarian hormone that is secreted by the ovaries and plays a role in terms of the development of secondary sexual characteristics such as the breasts, at the time of female puberty, or pubescence",
    "The ovarian hormone that is secreted by the ovaries and plays a role in the body in terms of the inhibition of follicle stimulating hormone among females",
    "The ovarian hormone that is secreted by the ovaries and plays a role as an androgen hormone",
    "The endocrine system gland that produces androgens, particularly testosterone, and, as a reproductive organ, the testes also produces and manufactures sperm",
    "A pituitary gland disorder",
    "A pituitary gland disorder",
    "A pituitary gland disorder.",
    "A pituitary gland disorder",
    "An overactive thyroid gland",
    "An underactive thyroid gland",
    "Disorder that results from the overproduction of cortisol by the adrenal glands",
    "Disorder that results from the underproduction of cortisol by the adrenal glands",
    "What?"
    ];

var answers=[
    "● The hypothalamus ● The pituitary gland ● The pineal gland ● The thyroid ● The parathyroid ● The adrenal glands ● The pancreas ● The ovaries ● The testes",
    "Hormones:",
    "Gland:",
    "Exocrine gland:",
    "Endocrine gland:",
    "Homeostasis:",
    "The hypothalamus:",
    "The pituitary gland:",
    "The pineal gland: ",
    "Circadian rhythm:",
    "Diurnal beings:",
    "Nocturnal beings:",
    "The thyroid:",
    "The parathyroids:",
    "Adrenal gland:",
    "Adrenal cortex:",
    "Adrenal medulla:",
    "The pancreas:",
    "The ovaries:",
    "Progesterone: ",
    "Estrogen:",
    "Inhibin:",
    "Androstenedione:",
    "The testes:",
    "Diabetes insipidus:",
    "Acromegaly:",
    "Gigantism:",
    "Syndrome of Inappropriate Antidiuretic Hormone Secretion (SIADH):",
    "Hyperthyroidism:",
    "Hypothyroidism:",
    "Cushing’s syndrome: ",
    "Addison’s disease:",
    "Next!"
];