"use strict";
//connect
console.log("Flashcard App Connected");
//Immune System - Terms and Terminology

/* Change the questions to whatever you want! Remember to stick to the theme of music this month. */
var questions=[
    "What?",
    "F01: Naturally occurring immune mechanisms",
    "F02: Immune mechanisms that occur as the result of the antigen-antibody response",
    "F03: The innate immune system's immune mechanisms",
    "F04: The acquired immune system's immune mechanisms",
    "F05: Ger_____. Is a microorganisms that cause infections",
    "F06: Pat_____. Is a microorganisms that cause infections",
    "F07: The manner with which infections are transmitted and carried",
    "F08: The part of the chain of infection that is the environment or habitat, within which the pathogen lives, grows and reproduces. Reservoirs can include humans, animals, water, soil and insects.",
    "F09: The part of the chain of infection that allows a pathogen, or disease causing germ, to move from its reservoir to its susceptible host.",
	"F10: The mode of transmission that occurs with direct contact with the pathogen",
    "F11: The mode of transmission that consists of direct contact with a spray of infectious material with can occur as the result of coughing and even speaking",
    "F12: The mode of transmission that involves the movement of an infectious agent from the reservoir to the host with inanimate, or nonliving, objects",
    "F13: The mode of transmission that occurs when the pathogen is carried in dust or droplets in the air that remain in place for a sufficiently enough time to infect a person exposed to this air",
    "F14: The mode of transmission that occurs when a person comes into contact with an infectious agent that is in water, blood, and even inanimate objects like a toy or a door knob",
    "F15: The mode of transmission that entails a mode of transportation with a vector which, unlike vehicles, are live beings like ticks and mosquitoes that spread infections with relatively direct mechanical means like an insect bite",
    "F16: Diseases causing pathogens that are spread and transmitted to others via contact with blood and other bodily fluids",
    "F17: Is a protein in the blood that is produced as the result of an exposure to an antigen or pathogen. They are protective proteins that bind to antigens and destroy them",
    "F18: A foreign and unnatural substance that provokes the body to produce antibodies to fight if off",
	"F19: The process with which a person becomes immune with an injection",
	"F20: Immunity that is acquired in a natural way",
	"F21: immunity that is NOT acquired in a natural way",
	"F22: Immunity that occurs as the result of getting a particular infection and also by being given an immunization against the particular infection, both of which will lead to the body's production of antibodies against the particular infection. Active immunity is long lived",
	"F23: Immunity that occurs without the antigen-antibody response, but instead, with the direct receiving of antibodies",
	"F24: Singular cell beings that appear as spirals, rods, spheres and other shapes and can be pathogenic, leading to infection and also releasing tissue damaging toxins",
	"F25: Pathogens are much smaller than bacteria; viruses have RNA, DNA and long molecules which comprise its genetic composition, a protein coat and an outer coating that contains lipids",
	"F26: The first stage of viral growth",
	"F27: The second stage of viral growth",
	"F28: The third stage of viral growth",
	"F29: The fourth stage of viral growth Self-assembly",
	"F30: The fifth stage of viral growth",
	"F31: Plant source microorganisms that affect human beings and typically classified as superficial, cutaneous, subcutaneous and systemic",
	"F32: Fungal infections that affect and infect the skin's epidermis and the hair",
	"F33: Fungal infections that include invasive hair and nail infections that goes beyond the epidermis",
	"F34: Fungal infections that infect all layers of the skin to the muscles and the fascia",
	"F35: Fungal infections that can affect the entire body; these infections are typically highly virulent and they can spread to virtually all organs of the body",
	"F36: A non living pathogen that consists of an abnormal folding of normal cellular, or prion, proteins",
	"F37: A living organism that lives on or in a host and gets its food from or at the expense of its host",
	"F38: Methods used to prevent the spread of infection. The two types of asepsis are medical asepsis, or clean procedure, and surgical, or sterile, asepsis.",
	"F39: Having been in contact with a microorganism. Sterile items are contaminated when sterile technique is not scrupulously followed and clean or medically aseptic items are contaminated when they have not been managed and handled to a manner that preserves the state of medical asepsis",
	"F40: Free from all living microorganisms",
	"F41: The destruction of all microorganisms and large numbers of bacterial spores with the use of a chemical or physical sterilizer",
	"F42: A germicidal solution that can be used on the skin to inhibit the growth of microorganisms, including pathogens",
	"F43: The physical, manual removal of visible material from a device or surface using scrubbing, water and a detergent or surfactant",
	"F44: The destruction of microorganisms including pathogens using a chemical or physical means of disinfection. Although disinfection destroys most pathogens, disinfection does not destroy spores",
	"F45: An infection caused by a microorganism that does not ordinarily cause disease but is capable of doing so under certain host conditions like a disease or disorder that adversely affects the person's immune system",
	"F46: Specialized equipment and attire that is used by employees in healthcare to protect against infections. Examples of personal protective equipment include gowns, gloves, goggles and respirators",
	"F47: Any disorder or treatment, like chemotherapy for cancer, that causes the immune system to be dysfunctional and not functioning correctly to protect the body",
	"F48: Human immunodeficiency virus and autoimmune deficiency syndrome are viral infections that lead the immune system to be dysfunctional and not functioning correctly to protect the body",
	"F49: The autoimmune disorder that leads to thyroid gland damage and dysfunction",
	"F50: A type of arthritis that is caused by an autoimmune disorder",
	"F51: Also referred to as lupus, this is a chronic autoimmune disorder that causes one's own immune system to destroy its own organs",
	"F52: The disorder that affects the thyroid gland and increases its activity",
	"F53: An autoimmune disorder that leads to hypothyroidism, or low thyroid functioning",
	"F54: An autoimmune disorder that leads to the lack of adrenal gland functioning",
	"F55: A type of arthritis that is caused by a systemic autoimmune disorder",
	"F56: A systemic autoimmune disorder that adversely affects the central nervous system"
    ];

var answers=[
    "Yes. Great!",
    "C01: Innate immune system",
    "C02: Acquired immune system",
    "C03: Nonspecific immune responses",
    "C04: Specific immune responses",
    "C05: Germs",
    "C06: Pathogens",
    "C07: Chain of infection",
    "C08: The reservoir",
    "C09: Mode of transmission",
	"C10: Direct contact transmission",
	"C11: Droplet transmission",
    "C12: Indirect contact transmission",
    "C13: Airborne transmission",
    "C14: Vehicle transmission",
    "C15: Vector transmission",
    "C16: Bloodborne pathogens",
    "C17: Antibody",
    "C18: Antigen",
    "C19: Immunization",
	"C20: Natural immunity",
	"C21: Artificial immunity",
	"C22: Active immunity",
	"C23: Passive immunity",
	"C24: Bacteria",
	"C25: Viruses",
	"C26: Attachment",
	"C27: Penetration",
	"C28: Uncoating",
	"C29: Replication",
	"C30: Release",
	"C31: Fungi",
	"C32: Superficial fungal infections",
    "C33: Cutaneous fungal infections",
    "C34: Subcutaneous fungal infections",
    "C35: Systemic fungi infections",
    "C36: A prion",
    "C37: A parasite",
    "C38: Asepsis",
    "C39: Contaminated",
	"C40: Sterile/sterility",
	"C41: Sterilization",
    "C42: Antiseptic",
    "C43: Cleaning",
    "C44: Disinfection",
    "C45: Opportunistic infection",
    "C46: Personal protective equipment (PPE)",
    "C47: Immunosuppression",
    "C48: HIV/AIDS",
    "C49: Hashimoto’s thyroiditis",
	"C50: Rheumatoid arthritis",
	"C51: Systemic lupus erythematosus",
	"C52: Grave's disease",
	"C53: Hashimoto’s thyroiditis",
	"C54: Addison’s disease",
	"C55: Rheumatoid arthritis",
	"C56: Multiple sclerosis"
];
