"use strict";
//connect
console.log("Flashcard App Connected");
//Digestive System-KeyTerms

/* Change the questions to whatever you want! Remember to stick to the theme of music this month. */
var questions=[
    "What?",
    "F01: The taking in of food and fluids through the mouth",
    "F02: Chewing",
    "F03: The products of protein digestion",
    "F04: The product of starch and carbohydrate digestion",
    "F05: The products of fat digestion",
    "F06: The orifice, or opening, through which the person ingests food and fluids",
    "F07: The muscular structure in the mouth that moves food around in the mouth to enable the swallowing of fluids and foods into the gastrointestinal tract.",
    "F08: Taste sensors found on the upper surface of tongue",
    "F09: The glands that manufacture and secrete a liquid called saliva which moistens the tongue and also perform a role in digestion",
	"F10: One of the salivary glands",
    "F11: One of the salivary glands that is under the lower jaw, or mandible",
    "F12: One of the salivary glands that is under the tongue",
    "F13: The digestive enzyme that is produced by the salivary glands in the saliva.",
    "F14: A part of the respiratory system and the gastrointestinal system that receives air from the nares and also receives food from the mouth",
    "F15: The 'flap' like projection in the back of the mouth that attached to the larynx. It goes up during breathing to allow the air to enter into the trachea during respirations and it moves down during the swallowing of food and drinking fluids to allow the food to enter the esophagus",
    "F16: The organ that produces bile which is then transported to the gallbladder through the common bile duct and then to the small intestine",
    "F17: The substance that is used for the breakdown and digestion of fats.",
    "F18: The ________ is a long straight hollow structure that starts at the pharynx and ends at the stomach that propels and moves food and fluids along the gastrointestinal tract with an action called peristalsis",
	"F19: Wave like involuntary muscular movements that move and propel food and fluids along the digestive tract",
	"F20: The hollow organ that collects and processes food after the food and fluids are propelled from the esophagus with peristalsis.",
	"F21: Chemical substances like pepsin, hydrochloric acid and gastric acid that digest foods",
	"F22: Partially digested food in the stomach",
	"F23: The primary organ of the digestive tract that is involved in the absorption phase of the digestive process",
	"F24: The first part of the small intestine that is attached to the stomach",
	"F25: The middle part of the small intestine",
	"F26: The last section of the small intestine that is attached to the large intestine",
	"F27: The primary organ of the digestive tract that is involved in the absorption phase of water and the removal of any remaining products or by products of digestion",
	"F28: Cec_______. One of the two parts of the large intestine",
	"F29: Col_______. One of the two parts of the large intestine",
	"F30: Asc_______colon. One of the four parts of the colon of the large intestine",
	"F31: Tra_______colon. One of the four parts of the colon of the large intestine",
	"F32: Dec_______colon. One of the four parts of the colon of the large intestine",
	"F33: Sig_______colon. One of the four parts of the colon of the large intestine",
	"F34: The last section of the gastrointestinal tract that evacuates wastes to the external environment with defecation",
	"F35: Including the jaw, face and abdominal area",
	"F36: The inadvertent or purposeful ingestion of toxic and/or caustic substances",
	"F37: Loose and often difficult to control fecal evacuation",
	"F38: The lack of a bowel movement and fecal evacuation",
	"F39: The drying of stool in the intestines that cannot be evacuated without special measures",
	"F40: Any object or abnormality that prevents the free passage of stool in the intestines",
	"F41: The pouching and distention of an intestinal area or areas",
	"F42: The inflammation or infection of an area or areas of the intestine affected with diverticulosis",
	"F43: The movement of acids and contents from the duodenum of the small intestine back into the esophagus",
	"F44: Erosions and sores in the stomach, esophagus and/or the small intestine",
	"F45: Gall bladder stones",
	"F46: An inflammation or infection of the gall bladder",
	"F47: Damage to the liver and its hepatic tissues",
	"F48: A type of liver infection",
	"F49: An acute or chronic inflammation of the colon",
	"F50: A chronic gastrointestinal disorder that includes the inflammation of the gastrointestinal tract",
	"F51: A disorder of the large intestine that can lead to abdominal pain, diarrhea and other gastrointestinal system disorders",
	"F52: Any malignancy from the mouth throughout the entire gastrointestinal system, including the rectum",
    "F53: Enlarged veins in the lower rectum and/or anus"
    ];

var answers=[
    "Yes. Great!",
    "C01: Ingestion",
    "C02: Mastication",
    "C03: Amino acids and peptides",
    "C04: Sugars",
    "C05: Glycerol and fatty acids",
    "C06: Mouth",
    "C07: Tongue",
    "C08: Taste buds",
    "C09: Salivary glands",
	"C10: Parotid salivary gland",
	"C11: Submandibular salivary gland",
    "C12: Sublingual salivary gland",
    "C13: Amylase",
    "C14: Pharynx",
    "C15: Epiglottis",
    "C16: Liver",
    "C17: Bile",
    "C18: Esophagus",
    "C19: Peristalsis",
	"C20: Stomach",
	"C21: Digestive enzymes",
    "C22: Chyme",
    "C23: Small intestine",
    "C24: Duodenum",
    "C25: Jejunum",
    "C26: Ileum",
    "C27: Large intestine",
    "C28: Cecum",
    "C29: Colon",
	"C30: Ascending colon",
	"C31: Transverse colon",
    "C32: Descending colon",
    "C33: Sigmoid colon",
    "C34: Rectum",
    "C35: Trauma to the face and gastrointestinal disorders",
    "C36: Poisonings",
    "C37: Diarrhea",
    "C38: Constipation",
    "C39: Fecal Impaction",
	"C40: Intestinal obstruction",
	"C41: Diverticulosis",
    "C42: Diverticulitis",
    "C43: Gastric acid reflux",
    "C44: Peptic ulcers",
    "C45: Cholelithiasis",
    "C46: Cholecystitis",
    "C47: Cirrhosis",
	"C48: Hepatitis",
	"C49: Colitis",
	"C50: Chiron's disease",
	"C51: Irritable bowel syndrome",
	"C52: Cancer",
    "C53: Hemorrhoids"
];

