"use strict";
//connect
console.log("Flashcard App Connected");
//Nervous System-KeyTerms

/* Change the questions to whatever you want! Remember to stick to the theme of music this month. */
var questions=[
    "What?",
    "F01: The primary nervous system cells",
    "F02: A type of nervous system cell, other than a neuron, that forms myelin which is the covering or sheath over parts of the neuron",
    "F03: The point at which neurons gently touch each other to send or receive a nerve impulse or message",
    "F04: The neurons that 'sense' and transmit information from the external environment",
    "F05: The neurons that send and transmit message that involve muscle movement.",
    "F06: Hearing, vision, smelling, tasting and touch",
    "F07: Nerves that send and receive motor function related nerve signals",
    "F08: Nerves that send and receive sensory function related nerve signals",
    "F09: Controls automatic and involuntary physiological functions of the body that are outside of our voluntary control",
	"F10: Controls voluntary physiological bodily functions such as voluntary muscular movements with the skeletal muscles of the body",
    "F11: The part of the nervous system that consists of the brain and the spinal cord",
    "F12: The protective membrane that covers the brain and the spinal cord",
    "F13: The innermost layer of the meninges",
    "F14: The middle layer of the meninges",
    "F15: The outermost layer of the meninges",
    "F16: The major organ of the body that controls and manages virtually all physiological and emotion bodily responses",
    "F17: The gray colored substance in the central nervous system that plays a higher role in the central nervous system's functioning than the white matter and the substance that contains myelinated neurons, unmyelinated neurons, glial cells, and circulatory capillaries",
    "F18: The substance in the central nervous system that plays a lesser role in the central nervous system's functioning than the gray and the substance that contains far fewer cells than the gray matter",
	"F19: The largest part of the brain that coordinates and enables bodily movement, sensory perception, learning, the sense of smell, the senses, memory, thinking, judgment and language and communication abilities",
	"F20: The part of the cerebrum that enables some of the senses, thinking, movement, judgment and a person's ability to write words, among other things",
	"F21: The part of the cerebrum that plays a role in terms of memory and hearing, among other things",
	"F22: The part of the cerebrum that plays a role in terms of sensory perception, among other things",
	"F23: The part of the cerebrum that plays a role in terms of vision and the ability to understand written language, among other things",
	"F24: The part of the brain that controls and manages bodily movement, balance,",
	"F25: The lower portion of the brain that connects to the spinal cord",
	"F26: The part of brainstem that controls messages sent from other higher areas of the brain to the pons and medulla below it and it also controls posture",
	"F27: The mid-section of the part of brain stem that connects to the midbrain above and the medulla below and the part that controls the rhythm of respirations",
	"F28: The lowest part of the brain stem that connects to the spinal cord below through a hole in the base of the skull called the foramen magnum and the part of the brainstem that controls many basic of vital signs and vital functions such as breathing and cardiac functioning",
	"F29: The part of the nervous system that consists of all parts of the nervous system with the exception of the brain and the spinal cord",
	"F30: The subsection of the nervous system that controls automatic and involuntary physiological functions of the body",
	"F31: The subsection of the nervous system that controls voluntary physiological bodily functions such as voluntary muscular movement with the skeletal muscles of the body",
	"F32: The part of the autonomic nervous system that prepares the body for the 'fight and flight' syndrome that result from stress like increased pulse and decreased peristalsis",
	"F33: The part of the autonomic nervous system THAT manages the other bodily functions that are NOT related to 'fight and flight' such as tear production and the production of saliva",
	"F34: A muscle reaction that automatically occurs in response to a certaintype of stimulus, or stimulation",
	"F35: The sensory cranial nerve that transmits the sense of smell or odor.",
	"F36: The sensory cranial nerve that transmits the sense of vision or sight.",
	"F37: The motor cranial nerve that transmits manages many eye movements",
	"F38: This motor cranial nerve also controls some eye movements.",
	"F39: This combination motor and sensory cranial nerve manages chewing",
	"F40: This primarily motor cranial nerve controls eye abduction.",
	"F41: This combination motor and sensory cranial nerve controls facial expressions, the tongue and the salivary glands.",
	"F42: This sensory cranial nerve transmits the sense of hearing",
	"F43: This combination motor and sensory cranial nerve controls gustatory or taste impulses and the secretion of saliva from the parotid gland.",
	"F44: This combination motor and sensory cranial nerve controls parts of the respiratory and the digestive systems such as the pharynx and swallowing.",
	"F45: This motor cranial nerve controls the movement of the trapezius and sternocleidomastoid muscles of the shoulder.",
	"F46: This motor cranial nerve speech and swallowing.",
	"F47: Abnormal nervous system nerve activity in the brain that can lead to a wide variety of signs and symptoms including uncontrolled bodily movement and jerking or a short lapse of consciousness",
	"F48: The progression of or sudden loss of the ability to be awake, alert and oriented",
	"F49: An episode of bleeding or a clot in the brain that causes symptoms and damage to the brain and its functioning",
	"F50: A traumatic head injury to the skull which is a closed space",
	"F51: A group of disorders that lead to seizures",
	"F52: An inflammation and infection of the meninges which is the outer layer of the brain and spinal cord",
	"F53: The neurological loss of function to one or more parts of the body",
	"F54: A traumatic injury to the spinal cord which leads to the lack of sensation and movement below the level of the injury",
	"F55: Impairments and losses relating to the senses such as sight, hearing, tasting, the sense of smell and the tactile, or touch, sense",
	"F56: A central nervous system disorder that can affect the spinal cord, the brain and vision",
	"F57: A chronic and progressive disorder of the nervous system that can lead to disability",
	"F58: A chronic and progressive disorder of the nervous system that leads to skeletal muscle weakness",
	"F59: A progressive degenerative form of dementia",
	"F60: A wide variety of malignant and benign in a part, or more than one part, of the nervous system",
	"F61: An often severe disorder of the fifth cranial nerve (the trigeminal neuralgia) that adversely affects the face",
	"F62: A disorder of the facial nerve that adversely affects the face and the muscular movements of the face",
    "F63: Pain originating from a nerve or group of nerves"  
    ];

var answers=[
    "Yes. Great!",
    "C01: Neurons",
    "C02: Glial cells",
    "C03: Synapse",
    "C04: Sensory neurons or nerves",
    "C05: Motor neurons or nerves",
    "C06: The senses",
    "C07: Efferent nerves",
    "C08: Afferent nerves",
    "C09: Autonomic nervous system",
	"C10: Somatic nervous system",
	"C11: Central nervous system",
	"C12: Meninges",
    "C13: Pia mater",
    "C14: Arachnoid",
    "C15: Dura mater",
    "C16: Brain",
    "C17: Gray matter",
    "C18: White matter",
    "C19: Cerebrum",
    "C20: The frontal lobe",
	"C21: The temporal lobe",
	"C22: The parietal lobe",
	"C23: The occipital lobe",
	"C24: Cerebellum",
	"C25: Brain stem",
	"C26: Midbrain",
	"C27: Pons",
	"C28: Medulla or medulla oblongata",
	"C29: Peripheral nervous system",
	"C30: Autonomic nervous system",
	"C31: The somatic nervous system",
	"C32: The sympathetic nervous system",
	"C33: The parasympathetic nervous system",
    "C34: Reflex",
    "C35: Olfactory nerve",
    "C36: Optic nerve",
    "C37: Oculomotor nerve",
    "C38: Trochlear nerve",
    "C39: Trigeminal nerve",
    "C40: Abducens nerve",
	"C41: Facial nerve",
	"C42: Acoustic nerve",
    "C43: Glossopharyngeal nerve",
    "C44: Vagus nerve",
    "C45: Spinal accessory nerve",
    "C46: Hypoglossal nerve",
    "C47: Seizures",
    "C48: Loss of consciousness",
    "C49: Stroke (cerebrovascular accident)",
    "C50: Closed head injury",
	"C51: Epilepsy",
	"C52: Meningitis",
	"C53: Paralysis",
	"C54: Spinal cord injuries",
	"C55: Impaired sensory perception",
	"C56: Multiple sclerosis",
	"C57: Parkinson's disease",
	"C58: Myasthenia gravis",
	"C59: Alzheimer's disease",
	"C60: Cancers and tumors of the brain",
	"C61: Trigeminal neuralgia",
	"C62: Bell's palsy",
    "C63: Neuralgia"   
];

