"use strict";
//connect
console.log("Flashcard App Connected");
//The Skeletal System-KeyTerms

/* Change the questions to whatever you want!*/
var questions=[
    "The majority of bones in the body which make up, for example, the skull, the ribs and the spinal column",
    "The bones which make up the rest of the skeletal system after the axial bones include the bones found in the upper limbs (arms), lower limbs (legs), shoulders and the pelvis.",
    "Flat bones like the sternum or the breast bone",
    "The bones of humerus which is the long bone of the arm and the femur which is the long bone of the leg",
    "Irregularly shaped bones like the sacrum and coccyx which make up the person's tailbone",    
    "Spongy bone which is not as strong and hard as cortical bone is",
    "Bone that is stronger than cancellous bone and the kind of bone that is most needed for bodily support and bodily movement",
    "The outer layer that covers all bones with the exception of long bones",
    "The lining around the innermost layer of the bone",
    "The innermost part of the bone which holds bone marrow.",
    "The cells in the bone that form the inner matrix of bone tissue that gives bones their strength",
    "The cells in the bone that break down bone and reabsorb it so that the bones can renew with remodeling and repair",
    "The cells in the bone that build new remodeled bones by producing new collagen and building new bone minerals",
    "The cells in the bone that are also called osteogenic cells and that form in the inner surface of the bone and they are somewhat immature osteoblasts that will later transform into osteoblasts",
    "The cells in the bone that protect the bones and they also release calcium into the blood when the blood calcium levels are low",
    "Connective tissue with collagen that connects bones to bones at the point where they articulate or come in close proximity to each other",
    "Connective tissue with collagen that connect bones to muscles and allow joint movement",
    "Connective tissue that connects muscles to other muscles",
    "Striated muscle like the skeletal muscles and those muscles that are restricted to only the heart",
    "Cells within cardiac muscle that contract the myocardium that are also referred to as cardiomyocytes",
    "Striated muscle that is voluntary muscle that enables the skeletal structures to move",
    "Involuntary muscles that control the movements and actions of the internal organs and systems of the body",
    "Movement away from the middle of the body",
    "Movement towards the middle of the body",
    "Movement that decreases, or lessens, the angle between two muscles or joints",
    "Movement that increases the angle between two muscles or joints",
    "The flexion of a joint that is beyond what it normally should do",
    "The extension of a joint that is beyond what it normally should do",
    "The circular movement of a joint or muscle that allows the bodily part to move in a circular manner.",
    "The muscular and joint movement that entails both circular movement and also movement away from the center of the body",
    "The muscular and joint movement that entails both circular movement and also movement towards the center of the body",
    "The muscular and joint movement that entails complete 3600 movement",
    "The turning of a joint inward",
    "The turning of a joint outward",
    "Movement of the foot (plantar) downward",
    "Movement of the foot (plantar) upward",
    "The specific movements or motions that each muscle is capable of.",
    "A fracture that involves the entire cross section of the fractured bone",
    "A fracture that affects only part of the bone and not the entire cross section",
    "A fracture that is stable and are not likely to be displaced",
    "A fracture that has displacement from its normal alignment",
    "A fracture that does not break through the surface of the skin",
    "A fracture that breaks through the skin surface to the exterior of the body",
    "A fracture that results from a disease process rather than undue stress or trauma as other fractures do.",
    "A fracture that occurs when only one side of the bone is fractured",
    "A fracture that occurs when a fragment of the fractured bone is pulled off the bone at its tendon or ligamentous attachment",
    "A fracture that occurs when splinters and small pieces of the fractured bone occur",
    "A fracture that occurs straight across the fractured bone.",
    "A fracture that occurs at an angle across the fractured bone",
    "A fracture that occurs when the pattern twists around the fractured bone",
    "A fracture that occurs when a bone fragment of the fractured bone is pushed and wedged into another bone fragment of the fractured bone",
    "A fracture that occurs when the fractured bone collapses as occurs with vertebral spinal fractures",
    "A fracture that occurs when bone fragments of the fractured bone are pushed in beyond the surrounding skin",
    "The joints are completely separated and are no longer articulated and connected with each other",
    "Only a partial, rather than a complete, displacement and separation of the joints or articular surfaces",
    "One of the many types of skeletal disorders that is characterized with the inflammation of one or more skeletal joints in the body",
    "A type of arthritis that affects the younger population",
    "is a disease that weakens bones to the point where they break easily — most often, bones in the hip, backbone (spine), and wrist.",
    "The type of arthritis that primarily affects the older population as their joints age, wear and tear.",
    "An infection of bone tissue",
    "A progressive degeneration of the Intervertebral discs in the spinal column",
    "The breakage of a bone",
    "What?"
    ];

var answers=[
    "Axial bones:",
    "Appendicular bones: ",
    "Flat bones: ",
    "Long bones:",
    "Irregular bones:",
    "Cancellous bone: ",
    "Cortical bone:",
    "Periosteum:",
    "Endosteum: ",
    "Medullary cavity: ",
    "Osteocytes: ",
    "Osteoclasts: ",
    "Osteoblasts:",
    "Stem cells:",
    "Lining cells:",
    "Ligaments:",
    "Tendons:",
    "Fascia:",
    "Cardiac muscle:",
    "Myocardiocytes:",
    "Skeletal muscle:",
    "Smooth muscle:",
    "Abduction: ",
    "Adduction: ",
    "Flexion:",
    "Extension:",
    "Hyperflexion:",
    "Hyperextension:",
    "Rotation:",
    "External rotation:",
    "Internal rotation:",
    "Circumduction:",
    "Inversion:",
    "Eversion:",
    "Plantar flexion:",
    "Dorsiflexion:",
    "Range of motion:",
    "Complete fracture:",
    "Incomplete fracture:",
    "Stable fracture:",
    "Unstable fracture:",
    "Closed fracture:",
    "Opened fracture:",
    "Pathological fracture:",
    "Greenstick fracture:",
    "Avulsion fracture:",
    "Comminuted fracture:",
    "Transverse fracture:",
    "Oblique fracture:",
    "Spiral fracture: ",
    "Impacted fracture:",
    "Compression fracture:",
    "Depressed fracture:",
    "Dislocation:",
    "Subluxation:",
    "Arthritis:",
    "Rheumatoid arthritis:",
    "Osteoporosis:",
    "Osteoarthritis:",
    "Osteomyelitis",
    "Intervertebral disc disease:",
    "Fractures:",
    "Next!"
];